version: '3.8'

services:
  # 1. Base de datos para el AuthService (.NET)
  postgres-db:
    image: postgres:16-alpine
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Base de datos para el ServerAdmin (Node)
  mongo-db:
    image: mongo:latest
    container_name: server-admin-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # 3. Microservicio de Autenticación (.NET)
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: src/Dockerfile
    container_name: auth-service
    ports:
      - "5065:8080"
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres-db;Port=5432;Database=auth_db;Username=postgres;Password=admin
      - Jwt__Key=clavesecreta123
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AuthService
    depends_on:
      postgres-db:
        condition: service_healthy

  # 4. Cliente Admin (React/Vite)
  client-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_URL=http://localhost:5065/api/v1
        - VITE_ADMIN_URL=http://localhost:5065/api/v1
    container_name: client-admin
    ports:
      - "5173:80"
    depends_on:
      - auth-service

volumes:
  pgdata:
  mongodata: